### ISSUE TITLE
Fedora 25 : Accessibility bus and AppIndicator3 issue ?

### ISSUE THREAD

**Issue by didli** [keithfancher/todo-indicator#3]
Hi ! Since my upgrade to F25, todo_indicator.py just gives an error message and ... nothing more happens. 
Here's the log : 
`** (todo_indicator.py:5639): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
/usr/lib/python2.7/site-packages/todotxt/indicator.py:23: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appindicator, \` 
Any idea what's going here please ^^ ?

**Comment by keithfancher** [comment]
Hello! I believe that warning is a red herring. The real issue was the `AppIndicator3` import. (They changed how it's imported in newer versions of the library.) This should be fixed as of version `0.6`. Thank you for filing!
