### ISSUE TITLE
Run editor asynchronously (for now it blocks even handler)

### ISSUE THREAD

**Issue by nick87720z** [keithfancher/todo-indicator#4]
I tried setup, where editor is go-for-it. As well as indicator is pointed to ~/Todo/todo.txt. When go-for-it is started not by indicator (from menu, panel, etc), everything is perfect - indicator immediately updates on every change from go-for-it.

But when it is started by indicator as editor, it doesn't update until go-for-it is closed. And though menu still may be opened, even manual update doesn't work.

**Comment by nick87720z** [comment]
Complementing, "Edit todo.txt" might be renamed to simple "Edit". Just to unload eyes a bit :)

**Comment by keithfancher** [comment]
Hello from the future! And thank you for taking the time to file this issue all those years ago.

I actually was never able to reproduce this, so I'm going to close it out. Feel free to re-open if it's still occurring on newer versions of `todo-indicator`.
